version: "3.9"
services:
  db:
    image: postgres:10.5
    container_name: postgres_db_container

    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yourDBName
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=fisuro@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports: 
  #     - '80:80'